apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ecart-deployment
spec:
  selector:
    matchLabels:
      app: ecart
  replicas: 2 
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ecart
          image: inshabano/ecart:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service 
metadata: 
  name: ecart-ssvc
spec:
  selector:
    app: ecart
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: LoadBalancer 
