apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: jenkins-serviceAccount
  namespace: webapps

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webapps
  name: app=role
rules:
  -apiGroups:
    - ""
    - apps
    - batch
    - asutoscallig
    - extensions
    - policy
    - rbac.authorization.k8s.io
  resources:
    - pods
    - configmaps
    - deamonsets
    - componentstatuses
    - events
    - horizxontalpodautoscalers
    - ingress
    - jobs
    - limitranges
    - namespaces
    - nodes
    - pods
    - persistentcvolumes
    - persistentvolumeclamis
    - resourcequotas
    - replicasets
    - serviceaccounts
    - services
  verbs: [ "get", "list", "delete", "watch", "update", "create", "patch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: webapps
subjects:
  - kind: ServiceAccount
    name: jenkins-serviceAccount
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-role
  apiGroup: rbac.authorization.k8s.io
